from datetime import datetime
from weasyprint import HTML


def generate_pdf(
    doctor_name: str,
    clinic_name: str,
    patient_name: str,
    patient_age: int | None,
    patient_sex: str | None,
    consultation_date: str,
    subjective: str,
    objective: str,
    assessment: str,
    plan: str,
) -> bytes:
    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body {{ font-family: Arial, sans-serif; margin: 48px; color: #1a1a2e; font-size: 12px; line-height: 1.5; }}
  .header {{ display: flex; justify-content: space-between; border-bottom: 2px solid #2563eb; padding-bottom: 16px; margin-bottom: 24px; }}
  .clinic-name {{ font-size: 20px; font-weight: bold; color: #2563eb; }}
  .doctor-name {{ font-size: 13px; color: #555; margin-top: 4px; }}
  .date-block {{ text-align: right; font-size: 12px; color: #555; }}
  .patient-box {{ background: #f0f4ff; border: 1px solid #d0d9f0; border-radius: 6px; padding: 12px 16px; margin-bottom: 24px; }}
  .patient-box table {{ width: 100%; border-collapse: collapse; }}
  .patient-box td {{ padding: 3px 8px; }}
  .label {{ font-weight: 600; color: #444; width: 140px; }}
  .section {{ margin-bottom: 22px; page-break-inside: avoid; }}
  .section-title {{
    font-size: 11px; font-weight: bold; color: #2563eb;
    text-transform: uppercase; letter-spacing: 0.8px;
    border-left: 3px solid #2563eb; padding-left: 8px;
    margin-bottom: 8px;
  }}
  .section-content {{ padding-left: 11px; white-space: pre-wrap; color: #222; }}
  .divider {{ border: none; border-top: 1px solid #e2e8f0; margin: 20px 0; }}
  .signature-block {{ margin-top: 48px; display: flex; justify-content: flex-end; }}
  .signature-inner {{ text-align: center; }}
  .signature-line {{ border-top: 1px solid #333; width: 180px; margin-bottom: 6px; }}
  .signature-name {{ font-weight: bold; font-size: 12px; }}
  .signature-sub {{ font-size: 10px; color: #666; }}
  .footer {{
    border-top: 1px solid #e2e8f0; padding-top: 10px; margin-top: 40px;
    font-size: 9px; color: #aaa; text-align: center;
  }}
</style>
</head>
<body>
<div class="header">
  <div>
    <div class="clinic-name">{clinic_name or 'Clinic'}</div>
    <div class="doctor-name">Dr. {doctor_name}</div>
  </div>
  <div class="date-block">
    <div>Date: {consultation_date}</div>
    <div>Clinical Note</div>
  </div>
</div>

<div class="patient-box">
  <table>
    <tr>
      <td class="label">Patient Name</td>
      <td>{patient_name}</td>
      <td class="label">Age / Sex</td>
      <td>{f'{patient_age} yrs' if patient_age else '—'} / {patient_sex or '—'}</td>
    </tr>
  </table>
</div>

<div class="section">
  <div class="section-title">S — Subjective (Chief Complaint &amp; History)</div>
  <div class="section-content">{subjective or 'Not documented.'}</div>
</div>

<hr class="divider">

<div class="section">
  <div class="section-title">O — Objective (Examination Findings)</div>
  <div class="section-content">{objective or 'Not documented.'}</div>
</div>

<hr class="divider">

<div class="section">
  <div class="section-title">A — Assessment (Diagnosis)</div>
  <div class="section-content">{assessment or 'Not documented.'}</div>
</div>

<hr class="divider">

<div class="section">
  <div class="section-title">P — Plan (Management)</div>
  <div class="section-content">{plan or 'Not documented.'}</div>
</div>

<div class="signature-block">
  <div class="signature-inner">
    <div class="signature-line"></div>
    <div class="signature-name">Dr. {doctor_name}</div>
    <div class="signature-sub">Digitally approved via Clinical Assistant</div>
  </div>
</div>

<div class="footer">
  Generated by Clinical Assistant &middot; {datetime.now().strftime('%d %b %Y, %I:%M %p')} &middot; For medical use only. This note was reviewed and approved by the treating physician.
</div>
</body>
</html>"""

    return HTML(string=html).write_pdf()
